Fix "indented block" linter error (#3468)
* fix: Fix mypy "indented block" error

Fix this [mypy error](https://github.com/getsentry/sentry-python/actions/runs/10390581522/job/28771379618):

```
sentry_sdk/integrations/opentelemetry/potel_span_processor.py:149: error: expected an indented block after function definition on line 31  [syntax]
```

Honestly not sure why this change fixes the problem, maybe there is some bug in `mypy`.

* fix: Fix other mypy syntax failures

After fixing the previous mypy failure, mypy discovered more syntax problems, which this commit fixes.

* fix: Correct typing in `potel_span_processor`

Fixing the original mypy error broke the typing; this change fixes the typing.