Handle ValueError in scope resets (#4928)
### Description
when async generators throw a `GeneratorExit` we end up with

```
ValueError: <Token var=<ContextVar name='current_scope' default=None at 0x7f04cf05fb50> at 0x7f04ceb17340> was created in a different Context
```

so just catch that and rely on GC to cleanup the contextvar since we
can't be smarter than that anyway for this case.

#### Issues
* resolves: #4925 
* resolves: PY-1886